[workspace]
resolver = "2"
members = [
    "draftsmith_render",
    "draftsmith_rs_api",
    "draftsmith_axum_web-app",
    # TODO: Right now this is in flask, but will become axum
    # "draftsmith_web_app",
]

