version: '3.8'

services:
  init_db:
    image: postgres:latest
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres-db
    command: ["sh", "/docker-entrypoint-initdb.d/init-db.sh"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/usr/src/app
    working_dir: /usr/src/app
    command: ["tail", "-f", "/dev/null"]
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres-db:5432/draftsmith2"
    depends_on:
      - postgres-db
      - init_db

  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
